name: nextgen
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  lazy_load_scrollview: ^1.3.0
  skeleton_text: ^3.0.0
  cupertino_icons: ^1.0.8
  lottie: ^2.3.1 
  flutter_staggered_grid_view: ^0.4.0
  url_launcher: ^6.1.10
  http: ^0.13.6  
  image_picker: ^0.8.7+1
  workmanager: ^0.5.1
  flutter_local_notifications: ^13.0.0
  web_socket_channel: ^2.4.0  
  expansion_tile_card: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/apa.jpg